import { useEffect, useState } from 'react'
import { AnimatePresence, motion, useScroll } from 'framer-motion'
import { ArrowDownRight, ArrowUpRight, ExternalLink, Mail, Menu, X, ZoomIn } from 'lucide-react'
import { achievements, certificates, education, experience, personal, projects, skills, type EvidenceItem } from './data/portfolio'

const reveal = { initial:{opacity:0,y:26}, whileInView:{opacity:1,y:0}, viewport:{once:true,amount:.18}, transition:{duration:.55,ease:'easeOut' as const} }

function Media({ item, className='' }:{item:EvidenceItem,className?:string}) {
  const [failed,setFailed] = useState(false)
  return <div className={'media '+className}>{!failed ? <img src={item.image} alt={`${item.title} preview`} onError={()=>setFailed(true)} /> : <div className="media-fallback"><span>IMAGE</span>Coming soon</div>}<div className="media-overlay"><ZoomIn size={18}/><span>View evidence</span></div></div>
}
function EvidenceModal({ item, onClose }:{item:EvidenceItem,onClose:()=>void}) {
  useEffect(()=>{ const close=(e:KeyboardEvent)=>e.key==='Escape'&&onClose(); document.addEventListener('keydown',close); return()=>document.removeEventListener('keydown',close) },[onClose])
  return <motion.div className="modal-backdrop" role="presentation" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={onClose}>
    <motion.section className="evidence-modal" role="dialog" aria-modal="true" aria-labelledby="evidence-title" initial={{opacity:0,y:25,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:16,scale:.98}} transition={{type:'spring',stiffness:260,damping:25}} onMouseDown={e=>e.stopPropagation()}>
      <button className="modal-close" onClick={onClose} aria-label="Close evidence"><X size={20}/></button><Media item={item} className="modal-media" />
      <div className="modal-copy"><p className="section-num">{item.kind.toUpperCase()}</p><h2 id="evidence-title">{item.title}</h2>{item.subtitle&&<h3>{item.subtitle}</h3>}<p>{item.description}</p>{item.details&&<div className="modal-details">{item.details.map(detail=><span key={detail}>{detail}</span>)}</div>}<div className="modal-actions">{item.url&&<a className="button primary" href={item.url} target="_blank" rel="noreferrer">{item.cta || 'Open link'} <ExternalLink size={16}/></a>}{item.githubUrl&&<a className="text-link" href={item.githubUrl} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={15}/></a>}{item.liveUrl&&<a className="text-link" href={item.liveUrl} target="_blank" rel="noreferrer">Live demo <ArrowUpRight size={15}/></a>}<button className="text-button" onClick={onClose}>Close</button></div></div>
    </motion.section>
  </motion.div>
}
function EvidenceCard({ item, onOpen }:{item:EvidenceItem,onOpen:()=>void}) { return <motion.article {...reveal} className={`evidence-card ${item.kind}`} whileHover={{y:-5}}><button onClick={onOpen} className="card-open" aria-label={`View ${item.title}`}><Media item={item}/></button><div className="evidence-copy"><p className="section-num">{item.eyebrow}</p><h3>{item.title}</h3>{item.subtitle&&<h4>{item.subtitle}</h4>}<p>{item.description}</p>{item.tags&&<div className="tags">{item.tags.map(tag=><span key={tag}>{tag}</span>)}</div>}<button className="text-button view-button" onClick={onOpen}>View evidence <ArrowUpRight size={15}/></button></div></motion.article> }
function Button({children,href,primary=false}:{children:React.ReactNode,href:string,primary?:boolean}) { return <a className={'button '+(primary?'primary':'')} href={href}>{children}<ArrowDownRight size={17}/></a> }
function Navbar(){ const [open,setOpen]=useState(false); const links=['About','Experience','Projects','Certifications','Skills','Contact']; return <><header><a className="brand" href="#home">AYUSHKUMAR<span>.</span></a><nav>{links.map(x=><a href={'#'+x.toLowerCase()} key={x}>{x}</a>)}</nav><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></header><AnimatePresence>{open&&<motion.div className="mobile-nav" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}>{links.map((x,i)=><motion.a initial={{opacity:0,x:-20}} animate={{opacity:1,x:0}} transition={{delay:i*.06}} onClick={()=>setOpen(false)} href={'#'+x.toLowerCase()} key={x}>{x}</motion.a>)}</motion.div>}</AnimatePresence></> }
function App(){ const [selected,setSelected]=useState<EvidenceItem|null>(null); const {scrollYProgress}=useScroll(); return <><motion.div className="scroll" style={{scaleX:scrollYProgress}}/><div className="ambient a"/><div className="ambient b"/><Navbar/><main id="home">
  <section className="hero"><motion.div {...reveal} className="hero-copy"><p className="eyebrow">SOFTWARE ENGINEER <i/> AI / ML <i/> FULL STACK</p><h1>Ayushkumar<br/><em>Vishwakarma</em></h1><p className="lede">Software Engineer with experience in enterprise retail applications, full-stack development, AI/ML, and data analytics.</p><p className="now">Currently working as an ETP POS Application Engineer at <b>Tata Trent.</b></p><div className="actions"><Button primary href="#projects">View my work</Button><a className="text-link" href="/resume.pdf" download>Download resume <ArrowDownRight size={16}/></a></div><div className="socials"><a href={`mailto:${personal.email}`} aria-label="Email Ayushkumar"><Mail/></a><a href={personal.github} target="_blank" rel="noreferrer" aria-label="GitHub">GH</a><a href={personal.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn">in</a></div></motion.div><motion.button className="profile-frame" onClick={()=>setSelected({title:personal.name,eyebrow:'PROFILE',kind:'profile',image:personal.profileImage,description:personal.profileDescription})} initial={{opacity:0,scale:.92}} animate={{opacity:1,scale:1}} transition={{delay:.2}} aria-label="Open profile image"><Media item={{title:'Profile placeholder',eyebrow:'PROFILE',kind:'profile',image:personal.profileImage,description:''}}/><span>PROFILE / 01</span></motion.button></section>
  <section className="cred"><span>8.55 <small>CGPA</small></span><span>IEEE <small>Xplore</small></span><span>HealthHack <small>Finalist</small></span><span>B.E. <small>Information Technology</small></span><span>Enterprise <small>Experience</small></span></section>
  <motion.section {...reveal} id="about" className="split about"><p className="section-num">01 / ABOUT</p><div><h2>A little about me.</h2><p className="big-copy">I enjoy working at the intersection of software engineering and intelligent systems—turning ideas into reliable, useful products.</p><p>I'm a B.E. Information Technology graduate from Datta Meghe College of Engineering (CGPA 8.55). My toolkit spans enterprise applications, SQL, Linux, Java, Python, AI/ML, and full-stack development.</p></div></motion.section>
  <section id="experience" className="section-block"><div className="heading"><p className="section-num">02 / EXPERIENCE</p><h2>Built close to<br/>the real world.</h2></div><div className="evidence-grid experience-grid">{experience.map(item=><EvidenceCard item={item} key={item.title} onOpen={()=>setSelected(item)}/>)}</div></section>
  <section id="projects" className="section-block"><motion.div {...reveal} className="heading"><p className="section-num">03 / SELECTED WORK</p><h2>Things I've built.</h2><p>Projects across AI/ML, full-stack development, and blockchain.</p></motion.div><div className="evidence-grid project-grid">{projects.map(item=><EvidenceCard item={item} key={item.title} onOpen={()=>setSelected(item)}/>)}</div></section>
  <section className="beyond"><p className="section-num">04 / BEYOND THE RESUME</p><h2>A few things worth seeing,<br/><em>not just reading about.</em></h2><div>{[['Experience',experience.length,'experience'],['Certifications',certificates.length,'certifications'],['Achievements',achievements.length,'achievements']].map(([label,count,anchor])=><a href={'#'+anchor} key={label as string}><span>{label}</span><b>{count}</b><ArrowDownRight/></a>)}</div></section>
  <section id="certifications" className="section-block"><div className="heading"><p className="section-num">05 / CERTIFICATIONS</p><h2>Learning, with<br/>receipts.</h2></div><div className="evidence-grid cert-grid">{certificates.map(item=><EvidenceCard item={item} key={item.title} onOpen={()=>setSelected(item)}/>)}</div></section>
  <section id="skills" className="skills"><motion.div {...reveal}><p className="section-num">06 / CAPABILITIES</p><h2>A practical<br/>technical range.</h2></motion.div><div className="skill-cloud">{Object.entries(skills).map(([category,items])=><div className="skill-group" key={category}><p>{category}</p>{items.map(x=><span key={x}>{x}</span>)}</div>)}</div></section>
  <section id="achievements" className="section-block"><div className="heading"><p className="section-num">07 / RECOGNITION</p><h2>Signals of curiosity.</h2></div><div className="evidence-grid achievement-grid">{achievements.map(item=><EvidenceCard item={item} key={item.title} onOpen={()=>setSelected(item)}/>)}</div></section>
  <section className="education"><p className="section-num">08 / EDUCATION</p><div className="edu-list">{education.map(item=><article key={item.institution}><h3>{item.institution}</h3><p>{item.program} <span>{item.period}</span></p><b>{item.detail}</b></article>)}</div></section>
  <motion.section {...reveal} id="contact" className="contact"><p className="section-num">09 / CONTACT</p><h2>Let’s build something<br/><em>worth talking about.</em></h2><p>Based in {personal.location}. I'm open to opportunities where I can learn, build, and contribute to meaningful engineering work.</p><div className="contact-details"><a className="text-link" href={`mailto:${personal.email}`}>{personal.email} <ArrowUpRight size={16}/></a><a className="text-link" href={`tel:${personal.phoneHref}`}>{personal.phone} <ArrowUpRight size={16}/></a></div></motion.section>
 </main><footer><div><b>AYUSHKUMAR VISHWAKARMA</b><span>Software Engineer · AI/ML · Full Stack</span></div><span>© 2026 Ayushkumar Vishwakarma</span><a href="#home">Back to top ↑</a></footer><AnimatePresence>{selected&&<EvidenceModal item={selected} onClose={()=>setSelected(null)}/>}</AnimatePresence></> }
export default App
